### ISSUE TITLE
ImportError following README QuickStart

### ISSUE THREAD

**Issue by RAvdek** [fridiculous/django-estimators#19]
Following the QuickStart in my terminal: Fails at initial migration.
```
$ pip install django-estimators
$ django-admin startproject estimators_sandbox
$ cd estimators_sandbox/
$ nano estimators_sandbox/settings.py 
# Here I add 'estimators' to my INSTALLED_APPS
$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/site-packages/estimators/models/__init__.py", line 1, in <module>
    from estimators.models.datasets import DataSet
  File "/usr/local/lib/python2.7/site-packages/estimators/models/estimators.py", line 5, in <module>
    from estimators import ESTIMATOR_DIR
ImportError: cannot import name ESTIMATOR_DIR
```

**Comment by sshniro** [comment]
Experienced the same issue. Using python 2.7 in virtualenv. Is there a work around for this issue ?
